### ISSUE TITLE
Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by tumbone** [tumbone/mean-app-boilerplate#2]
`$ karma init 
> readline.js:525
  this.line = this.line.slice(this.cursor);
                       ^

TypeError: Cannot read property 'slice' of undefined
    at Interface._deleteLineLeft (readline.js:525:24)
    at suggestNextOption (C:\Users\Oliver\Projects\absync\node_modules\karma\lib\init\state_machine.js:43:9)
    at nextQuestion (C:\Users\Oliver\Projects\absync\node_modules\karma\lib\init\state_machine.js:119:12)
    at process (C:\Users\Oliver\Projects\absync\node_modules\karma\lib\init\state_machine.js:135:10)
    at Object.exports.init (C:\Users\Oliver\Projects\absync\node_modules\karma\lib\init.js:247:6)
    at Object.exports.run (C:\Users\Oliver\Projects\absync\node_modules\karma\lib\cli.js:237:25)
    at requireCliAndRun (C:\Users\Oliver\AppData\Roaming\npm\node_modules\karma-cli\bin\karma:44:16)
    at C:\Users\Oliver\AppData\Roaming\npm\node_modules\karma-cli\bin\karma:54:12
    at C:\Users\Oliver\AppData\Roaming\npm\node_modules\karma-cli\node_modules\resolve\lib\async.js:44:21
    at ondir (C:\Users\Oliver\AppData\Roaming\npm\node_modules\karma-cli\node_modules\resolve\lib\async.js:187:31)
    at C:\Users\Oliver\AppData\Roaming\npm\node_modules\karma-cli\node_modules\resolve\lib\async.js:153:39
    at onex (C:\Users\Oliver\AppData\Roaming\npm\node_modules\karma-cli\node_modules\resolve\lib\async.js:93:22)
    at C:\Users\Oliver\AppData\Roaming\npm\node_modules\karma-cli\node_modules\resolve\lib\async.js:24:18
    at FSReqWrap.oncomplete (fs.js:82:15)`

Reference:
[karma-runner/karma Issue #1724](https://github.com/karma-runner/karma/issues/1724)
[karma-runner/karma Issue #2045](https://github.com/karma-runner/karma/issues/2045)

**Comment by tumbone** [comment]
**FIX:**
[Suggested Fix from a user](https://github.com/karma-runner/karma/issues/2045#issuecomment-245275134)

Probably you're using the Git Bash terminal, MinTTY, which doesn't have full support for TTY.

4 options to fix the problem:

1. Use CMD terminal with the Windows shell (the default Windows console)
2. Use CMD terminal with the Bash shell (execute "C:\Program Files\Git\bin\bash.exe" --login -i in cmd terminal)
3. Use Powershell (an alternative terminal typically installed by default in Windows environments)
4. Use an alternative terminal 

If you just need execute isolated interactive commands like karma init, I recommend option 1 for it and then come back to Git Bash. However I would give a try to Powershell.
